# https://github.com/helaili/jekyll-action
#
name: Testing the GitHub Pages publication

on:
  push:
    branches:
      - master
    paths:
      - 'soirbhiochas/**'
      - 'build.sh'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'suspected_typos.txt'
      - '.github/workflows/visualizations.yml'
      - '.github/workflows/jekyll.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Python visualization
    steps:
    - uses: addnab/docker-run-action@v3
      with:
        image: python:3.10
        run: ./build.sh
      name: Run soirbhiochas
    - name: Commit visualization changes
      run: |
        git config --global user.name 'Phil Weir (via action)'
        git config --global user.email 'phil.t.weir@gmail.com'
        git commit -am "Automated visualization build" docs/
        git push
